
default: &default
  adapter: postgresql
  encoding: utf8
  database: photoapp_dev
  username: rolph
  password: '*'


development:
  adapter: postgresql
  encoding: utf8
  database: photoapp_dev
  username: rolph
  password: '*'

production:
  adapter: postgresql
  encoding: utf8
  database: photoapp_production
  username: rolph
  password: '*'