# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82c81bc056f3e6965f419ecd48802da67bf6bd7a296ecf894128b773eda97e05b9ec0a099ec9715bde0969c93872b1dd5ea01954d92e1562167676c0ca084c69

test:
  secret_key_base: 251f191469913dbeaf714e55a69738619d95c1341f126be85bb3781c4468d891475599c8e90ae6fab4e60e2640372255911e94466b0ea9a32144bf6052f67567

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
